name: Publish beta

on:
  pull_request:
    branches:
      - master

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: restore lerna
        uses: actions/cache@master
        with:
          path: |
            node_modules
            */*/node_modules
          key: ${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}
      - uses: actions/setup-node@v1
        with:
          registry-url: "https://npm.pkg.github.com"
      - name: Install dependencies
        run: yarn install
      - name: Publish stable to Github Packages
        run: yarn run release-beta
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
